[package]
name = "spatialshot-setup"
description = "Spatialshot setup wizard"
authors = ["a7mddra"]
license = "Apache-2.0"
repository = "https://github.com/a7mddra/spatialshot.git"
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = [] }
tauri-plugin-shell = "2.0.0"
tauri-plugin-dialog = "2.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12", features = ["blocking", "stream"] }
zip = "6.0.0"
fs_extra = "1.3"
tempfile = "3.8"
dirs = "6.0.0"

[target.'cfg(not(target_os = "linux"))'.dependencies]
interprocess = "2.2.1"
