[package]
name = "kernel"
version = "1.0.0"
edition = "2021"
authors = ["a7mddra-spatialshot"]
description = "Core orchestrator for the Spatialshot utility"
license = "Apache-2.0"

[[bin]]
name = "kernel"
path = "source/main.rs"

[dependencies]
anyhow = "1.0"
home = "0.5"
fs2 = "0.4"
sysinfo = "0.37.2"
which = "8.0.0"
dirs = "6.0.0"
rdev = "0.5.3"
parking_lot = "0.12"
env_logger = "0.11"
log = "0.4"
regex = "1.10"

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = "0.23" 

[profile.release]
lto = true
strip = true
opt-level = 'z'
codegen-units = 1
panic = 'abort'

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
] }
