[package]
name = "kernel"
version = "1.0.0"
edition = "2021"
authors = ["a7mddra-spatialshot"]
description = "Core orchestrator for the Spatialshot utility"
license = "Apache-2.0"

[[bin]]
name = "sshot"
path = "source/main.rs"

[dependencies]
anyhow = "1.0"
home = "0.5"
fs2 = "0.4"
sysinfo = "0.32.0"
which = "6.0"
uuid = { version = "1.10", features = ["v4", "fast-rng"] }
dirs = "5.0"

[profile.release]
lto = true
strip = true
opt-level = 'z'
codegen-units = 1
panic = 'abort'

[target.'cfg(windows)'.dependencies]
windows = { version = "0.56.0", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
] }