[package]
name = "spatialshot-orchestrator"
version = "0.1.0"
edition = "2021"
authors = ["a7mddra-spatialshot"]
description = "Core orchestrator for the SpatialShot utility"
license = "GPL-3.0"

[dependencies]
anyhow = "1.0"
log = "0.4"
env_logger = "0.11"
core_affinity = "0.8"
home = "0.5"
notify = "6.1"
sysinfo = "0.30"
fs2 = "0.4"

[profile.release]
lto = true
strip = true
opt-level = 'z'
codegen-units = 1
panic = 'abort'

[target.'cfg(windows)'.dependencies]
windows = { version = "0.56.0", features = [
    # "core", <-- REMOVE THIS LINE
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_System_RemoteDesktop",
    "Win32_Security",
    "Win32_System_Environment",
    "Win32_System_Pipes",
    "Win32_UI_WindowsAndMessaging",
] }