name: Build Orchestrator

on:
  workflow_dispatch:
  # push:

jobs:
  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install MUSL target
      run: rustup target add x86_64-unknown-linux-musl

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y musl-tools musl-dev libudev-dev libdbus-1-dev
    
    - name: Update dependencies
      working-directory: ./packages/orchestrator
      run: cargo update

    - name: Build release (static MUSL)
      working-directory: ./packages/orchestrator
      run: cargo build --release --target x86_64-unknown-linux-musl

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: spatialshot-orchestrator-linux-x64
        path: packages/orchestrator/target/x86_64-unknown-linux-musl/release/spatialshot-orchestrator
        if-no-files-found: error

  build-macos:
    name: Build (macOS)
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update dependencies
      working-directory: ./packages/orchestrator
      run: cargo update

    - name: Build release
      working-directory: ./packages/orchestrator
      run: cargo build --release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: spatialshot-orchestrator-macos-x64
        path: packages/orchestrator/target/release/spatialshot-orchestrator
        if-no-files-found: error

  build-windows:
    name: Build (Windows)
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Update dependencies
      working-directory: ./packages/orchestrator
      run: cargo update

    - name: Build release
      working-directory: ./packages/orchestrator
      run: cargo build --release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: spatialshot-orchestrator-windows-x64.exe
        path: packages/orchestrator/target/release/spatialshot-orchestrator.exe
        if-no-files-found: error

